#!/bin/bash

usage()
{
cat << EOF
usage: $0 COMMAND

This script sets up the TCDDocProc arch environment for Ubuntu.

COMMANDS:
    install    Installs Arch for Ubuntu
    run        Run Python server (skips installation)
    test       Run unit tests for the system
EOF
}

install()
{
    sudo apt-get -y install python python-dev python-setuptools check sqlite3 cython
    sudo apt-get install -y curl
    curl -sL https://deb.nodesource.com/setup | sudo bash
    sudo apt-get install -y nodejs
    sudo rm -rf venv

    # install yuglify
    sudo npm install -g yuglify

    # install bower
    sudo npm install -g bower

    # install coffee-script
    sudo apt-get install -y coffeescript

    # install sass and compass
    sudo apt-get install -y rubygems
    sudo gem install compass -V --no-ri --no-rdoc

    # needed by scss compiler
    sudo gem install json -V --no-ri --no-rdoc
    sudo easy_install virtualenv virtualenvwrapper pip
    git config --global url."https://github.com".insteadOf "git://github.com"

    rm -rf venv
    virtualenv venv
    source venv/bin/activate
    pip install -r app/requirements.txt
}

run()
{
    source venv/bin/activate
    pip install -r app/requirements.txt
    export DEBUG=False
    export LOCAL=True
    sudo rm -rf app/collectstatic
    cd app;
    mkdir collectstatic
    mkdir collectstatic/bower_components
    python ./manage.py bower install
    cd ../;
    python app/manage.py collectstatic --noinput
    python app/manage.py migrate
    sudo chmod 777 app/collectstatic/xml/pathways.xml
    python app/manage.py runserver
}

test()
{
    source venv/bin/activate
    pip install -r app/requirements.txt
    python app/manage.py test processes openemr core
}

case $1 in
    install)
        install
        exit 1
        ;;
    run)
        run
        exit 1
        ;;
    test)
        test
        exit 1
        ;;
    *)
        usage
        exit 1
        ;;
esac
