#!/bin/bash

# Install homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install virtualbox
brew install caskroom/cask/brew-cask
brew cask install virtualbox

# Install docker
brew install docker
brew install boot2docker

# For watch
brew install entr

# Start boot2docker
boot2docker init
boot2docker up

# Build and run web app
docker build -t webapp .
