#!/bin/bash
docker stop $(docker ps -a -q) >/dev/null 2>&1
PID=$(docker run -d -p $1:80 -v $(pwd):/home/docker/code:rw webapp) >/dev/null 2>&1
docker exec $PID python /home/docker/code/app/manage.py collectstatic --noinput >/dev/null 2>&1
echo $PID
