#!/bin/bash

echo "Starting..."

PID=$(./run $1)

echo "Running on: http://$(boot2docker ip):$1"

docker exec $PID python /home/docker/code/app/manage.py migrate&>/dev/null

find . -type f \( -iname '*.coffee' -o -iname '*.scss' -o -iname '*.css' -o -iname '*.js' -o -iname '*.xml' \) | entr \
	docker exec $PID python /home/docker/code/app/manage.py collectstatic --noinput &

find . -type f \( -iname '*.py' \) | entr \
	./run $1 | read PID
